"""create products table

Revision ID: 0d5520181e64
Revises: 90b9f8a748a4
Create Date: 2026-06-03 19:19:02.043780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5520181e64'
down_revision: Union[str, Sequence[str], None] = '90b9f8a748a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('data_validade', sa.Date(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_id'), 'produtos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_produtos_id'), table_name='produtos')
    op.drop_table('produtos')
    # ### end Alembic commands ###
